### ISSUE TITLE
TypeError when running on (possibly invalid) json

### ISSUE THREAD

**Issue by famosab** [crs4/rocrate-validator#28]
I installed the validator via pip and tried to run it on a file I created with a development version of the nf-prov plugin. The following error occured. Any help is welcome :)

```
rocrate-validator validate ro-crate-metadata.json

Traceback (most recent call last):
  File "/home/paifb01/mambaforge/envs/roc/bin/rocrate-validator", line 5, in <module>
    from rocrate_validator.cli import cli
  File "/home/paifb01/mambaforge/envs/roc/lib/python3.8/site-packages/rocrate_validator/cli/__init__.py", line 15, in <module>
    from .commands import profiles, validate
  File "/home/paifb01/mambaforge/envs/roc/lib/python3.8/site-packages/rocrate_validator/cli/commands/profiles.py", line 24, in <module>
    from rocrate_validator import services
  File "/home/paifb01/mambaforge/envs/roc/lib/python3.8/site-packages/rocrate_validator/services.py", line 39, in <module>
    def detect_profiles(settings: Union[dict, ValidationSettings]) -> list[Profile]:
TypeError: 'type' object is not subscriptable
```

**Comment by famosab** [comment]
Upgrading to the latest Python version seems to have fixed the issue for me :)

**Comment by famosab** [comment]
> I suspected that would be a solution :-) What version are you using now?

3.13

**Comment by ilveroluca** [comment]
Thanks for your feedback.
